### ISSUE TITLE
MIUI V7 recompiling errors 

### ISSUE THREAD

**Issue by Bormental** [BurgerZ/jBART#103]
To recompile miui v7 apps newer apktool is needed. Otherwise we get errors like

[13.08.2015 14:23:43.362] W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x100d0051

Could you please update apktool in jBART.

**Comment by Bormental** [comment]
Apktool 2.0.1 works fine.

**Comment by BurgerZ** [comment]
I'll upload new jbart version tomorrow.

**Comment by jaymeferreyra** [comment]
Excellent. 
Thanks BurgerZ

**Comment by BurgerZ** [comment]
Had no time to finish some modules, so wait a little more :)

**Comment by gkalen** [comment]
Don't forget to support this project for windows users too.
My best regards and keep up the good work.
