### ISSUE TITLE
After Recompile MIUI 7 on redmi note 2 cannot recieve sms 

### ISSUE THREAD

**Issue by igobig** [BurgerZ/jBART#114]
jBART last version After Recompile MIUI 7 on redmi note 2 cannot recieve sms

**Comment by BurgerZ** [comment]
Do you recompile FwkPlugin.apk?

**Comment by igobig** [comment]
yep, I recompile FwkPlugin.apk

**Comment by BurgerZ** [comment]
do not do it!

**Comment by igobig** [comment]
I have copy stock FwkPlugin.apk replace in system/plugin issue still same again

**Comment by BurgerZ** [comment]
This is not jbar related problem. It's signature verification problem (any manipulations with plugins, such as deodexing, recompiling, etc. change signatures, so these apps won't work)
