### ISSUE TITLE
Extract aditional data from MiuiSystemUI.apk and Music.apk

### ISSUE THREAD

**Issue by ygorigor** [BurgerZ/jBART#115]
Could you add an option to jBART that will add translated strings to statusbar_clock.maml and statusbar_music.maml when MiuiSystemUI.apk is decompiled or compiled, and that will add lang.js to static.zip from Music.apk

**Comment by BurgerZ** [comment]
Closing this, as you can translate files, and place them into the rom by replacements repo.
