### ISSUE TITLE
Problem deodex android 5.0 and 5.1 Jbart 3h

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#125]
Hello Andrei, thanks for the new Jbart, but there is still the problem of deodex Android 5.x latest release team miui removed rom file "boot.oat" which was used to make the deodex, therefore remains the problem building deodex Rom.

**Comment by ingbrzy** [comment]
will be back tomorrow..

**Comment by ale8530** [comment]
Thanks ingbirzy closed this issue

**Comment by BurgerZ** [comment]
That was crappy builds (5.11.19) from our chinese friends. That builds are deodexed already, but .odex files was present in roms anyway. Just check for classes.dex files inside of every app in the rom and you will see.
I'll add these checks to the deodexer.

**Comment by ale8530** [comment]
Thanks Andrei :)
