### ISSUE TITLE
Bootloop using latest version (Redmi 2 / MIUI7)

### ISSUE THREAD

**Issue by mattbittencourt** [BurgerZ/jBART#126]
Hi,

I was using the old version (20150824) and switched to the newer one. I've corrected settings and removed all json patches (which doesnt have support anymore). But after compiling the same rom with the same sources selected and same group of patches, I get a bootloop using the latest version (20151126.00) with the following error:

E/AndroidRuntime( 3442): *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
E/AndroidRuntime( 3442): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 3442): 	at com.android.server.am.ExtraActivityManagerService.<clinit>(ExtraActivityManagerService.java:189)
E/AndroidRuntime( 3442): 	at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:1993)
E/AndroidRuntime( 3442): 	at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:210)
E/AndroidRuntime( 3442): 	at com.android.server.am.ActivityManagerService$AThread.run(ActivityManagerService.java:1866)
E/AndroidRuntime( 3442): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x11060008
E/AndroidRuntime( 3442): 	at android.content.res.Resources.getValue(Resources.java:1133)
E/AndroidRuntime( 3442): 	at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
E/AndroidRuntime( 3442): 	at android.content.res.Resources.getInteger(Resources.java:917)
E/AndroidRuntime( 3442): 	at android.provider.MiuiSettings$System.<clinit>(MiuiSettings.java:790)
E/AndroidRuntime( 3442): 	... 4 more
E/AndroidRuntime( 3442): Error reporting crash
E/AndroidRuntime( 3442): java.lang.NullPointerException
E/AndroidRuntime( 3442): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:84)
E/AndroidRuntime( 3442): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime( 3442): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
I/ServiceManager(  203): service 'power' died

I haven't altered any of the binaries, and I'm using the default apktool provided. 
Any clues of what it might be? I've checket all my rom files searching for that missing resource, and there's no mention of it anywhere.

**Comment by BurgerZ** [comment]
Do you use jbart in Windows? If so, I wrote that NO support for MIUI v7 in Windows (only linux x64)!

**Comment by mattbittencourt** [comment]
Im on ubuntu 14.04, never used it over windows.

**Comment by BurgerZ** [comment]
Try with 20151230.03 build: https://github.com/BurgerZ/jBART/commit/4636abffa81fef978d64cccce74cdf861680444e
