### ISSUE TITLE
finished rom could not be installed(signature failed)

### ISSUE THREAD

**Issue by xnk06** [BurgerZ/jBART#127]
i tried to translate latest rom update for redmi note2(7.0.8.0/5.0.2) and mi4c (7.0.11.0/5.1.1).
when i installed it to the phone with original recovery, it stops after few percents (it says Error applying update.zip - signature verification failed). 
but if i install it using custom recovery(twrp), it loads 100%, but when the phone boots into menu, i see no translation was made (the setting menu doesnt show up a new language option)
any suggestion? i use jbart3h on ubuntu 64bit, no error report log after installation finished, tried four repo/translation but same result

**Comment by BurgerZ** [comment]
That's not jbart related issue.
You have to go to the miui.com forum and find info, which says that these devices (MiNote Pro also) has signature-protection in default recovery, so you have to use custom recoveries to install custom roms.
