### ISSUE TITLE
No jbart exe?

### ISSUE THREAD

**Issue by exodius48** [BurgerZ/jBART#129]
Hi, why on latest no .exe file? Can you upload exe ?

**Comment by jaymeferreyra** [comment]
The new jbart is only working in Linux (like the previous version).
But you can open it on Windows with double click in jar file

**Comment by BurgerZ** [comment]
@jaymeferreyra, new jbart works in any OS with java support!
Only MIUI v7 compiling works (partially) in Linux (x64).

**Comment by jaymeferreyra** [comment]
Sorry for my mistake BurgerZ. 
I only compile miui 7 and I forget the others releases with android base.

**Comment by exodius48** [comment]
I just create .bat file to replace .exe file , and i'ts work for me 
here the file http://rghost.net/8DdHC28NY
please make .exe file if possible.

**Comment by cpasmoi** [comment]
why bother with .bat and other stuff ? just double click on the file

**Comment by exodius48** [comment]
Because i replace .jar association with winrar.

**Comment by BurgerZ** [comment]
so .bat is not enough?

**Comment by exodius48** [comment]
Bat is enough, but .exe would be nice. :dancer:

**Comment by ale8530** [comment]
Not worked on windows with file .bat.
![immagine](https://cloud.githubusercontent.com/assets/6189615/11589389/662e8374-9a88-11e5-84c7-512fac74db62.png)


How can I fix?

**Comment by BurgerZ** [comment]
You have to use Java 8

**Comment by ale8530** [comment]
ok ;) Thanks
