### ISSUE TITLE
Redmi 1S V7.1.1.0.KHCMICK compiling errors

### ISSUE THREAD

**Issue by ilopez85** [BurgerZ/jBART#133]
1. NetworkAssistant2.apk
2. Provision.apk
3. XiaomiAccount.apk
4. CloudBackup.apk
5. Mms.apk
6. Settings.apk

[miui-7-20151201-7.1.1.0-armani.zip.compiler.log.zip](https://github.com/BurgerZ/jBART/files/69818/miui-7-20151201-7.1.1.0-armani.zip.compiler.log.zip)

**Comment by Fays** [comment]
Hello this is a problem in the framework miui system must be added in the
apktool.yml - 18 and compilation works

**Comment by ilopez85** [comment]
Thanks for your answer ;). Can you explain me how to do it?

**Comment by ilopez85** [comment]
in which apktool.yml file I must to add -18?

**Comment by BurgerZ** [comment]
Deodexer fixed at https://github.com/BurgerZ/jBART/commit/4636abffa81fef978d64cccce74cdf861680444e
Closing this as solved (via patch, but solved)
