### ISSUE TITLE
Redmi 1S V7.1.1.0.KHCMICK doesn't boot after deodex it

### ISSUE THREAD

**Issue by ilopez85** [BurgerZ/jBART#134]
Redmi 1S V7.1.1.0.KHCMICK doesn't boot after deodex it, deodex log not show any error but ROM get into bootloop... :( anyone else with this problem?

**Comment by jaymeferreyra** [comment]
Yes.
You can't deodex Redmi 1S and Redmi Note LTE with last jbart, you must do it with jbart released on august.

**Comment by BurgerZ** [comment]
wow, thanks, I'll check it.

**Comment by ilopez85** [comment]
Where can I download that version? (and older versions of jBART)

**Comment by BurgerZ** [comment]
https://github.com/BurgerZ/jBART/archive/67b9753229a438f6a345ce08b7f96fffcd0bd698.zip

**Comment by ilopez85** [comment]
thanks! ;)

**Comment by BurgerZ** [comment]
@ilopez85 will you have some time tomorrow to test deodexer? I'll try to fix it.

**Comment by ilopez85** [comment]
of course

**Comment by jaymeferreyra** [comment]
BurgerZ
This happens with Miui V7 4.4.4
I have another issue with Xiaomi Redmi Note 2 with android 5.0 (hermes), after deodex it can't received sms, because the plugins can't be deodexed.

Thanks for your work ;)

**Comment by BurgerZ** [comment]
@jaymeferreyra no, you have to patch plugins signature checker, email me for the patch.

**Comment by jaymeferreyra** [comment]
Done
Thanks ;)

**Comment by ilopez85** [comment]
Does that patch only affects lollipop?

**Comment by BurgerZ** [comment]
this patch only affects Hermes

**Comment by BurgerZ** [comment]
@ilopez85 email me, please, I'll send you the test jbart build.

**Comment by ilopez85** [comment]
Test build works OK deodexing MIUI 7 for Redmi 1S :)

**Comment by ale8530** [comment]
Confirmed this bug armani and hammerhead

**Comment by BurgerZ** [comment]
fixed, wait for update.

**Comment by ale8530** [comment]
Thanks

**Comment by BurgerZ** [comment]
Fixed (tested) at https://github.com/BurgerZ/jBART/commit/4636abffa81fef978d64cccce74cdf861680444e
