### ISSUE TITLE
TrafficControl.apk decompiling error

### ISSUE THREAD

**Issue by ilopez85** [BurgerZ/jBART#135]
Redmi 1S (no patchrom). I also still having problems to compile some applications (NetworkAssistant2.apk Provision.apk XiaomiAccount.apk CloudBackup.apk Mms.apk Settings.apk). In global stable version 7.0.5.0 everything was OK, I don't know exactly from which version the problems started :(.

[miui-7-20151224-5.12.24-armani.zip.decompiler.log.zip](https://github.com/BurgerZ/jBART/files/77198/miui-7-20151224-5.12.24-armani.zip.decompiler.log.zip)

[miui-7-20151224-5.12.24-armani.zip.compiler.log.zip](https://github.com/BurgerZ/jBART/files/77208/miui-7-20151224-5.12.24-armani.zip.compiler.log.zip)

**Comment by BurgerZ** [comment]
What is the source of this rom? miui-7-20151224-5.12.24-armani.zip
This is not official armani rom. Patchrom (as miui.system appears after patchrom)?

**Comment by ilopez85** [comment]
miui-7-20151224-5.12.24-armani.zip is the same as:

http://bigota.d.miui.com/5.12.24/miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip

renamed by me after deodex it to differentiate both (odexed and deodexed)

**Comment by ilopez85** [comment]
[miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.deodexer.log.zip](https://github.com/BurgerZ/jBART/files/78936/miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.deodexer.log.zip)

[deodexed_miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.decompiler.log.zip](https://github.com/BurgerZ/jBART/files/78937/deodexed_miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.decompiler.log.zip)

[deodexed_miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.compiler.log.zip](https://github.com/BurgerZ/jBART/files/78935/deodexed_miui_HM1SWCGlobal_5.12.24_34be53c955_4.4.zip.compiler.log.zip)

**Comment by BurgerZ** [comment]
Use simple patches for workaround:
For each errorneous apk use patch like this:
````
appfile <NetworkAssistant2.apk>;
# Fix No resource found ...@miui.system:...
replaceinfile "%res%/../apktool.yml" "  - 16" "  - 16\n  - 18";
````

**Comment by ilopez85** [comment]
One patch for each app, or one patch for all?

**Comment by BurgerZ** [comment]
1 for each, ofcourse

**Comment by BurgerZ** [comment]
Closing this as it could be solved by a patch
