### ISSUE TITLE
Deodex Redmi Note 2 problem sending and receiving text message

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#136]
I wanted to point out that after the deodex the terminal does not receive or send text messages.

Solvable problem by putting files:

framework/ arm/boot.oat
framework/arm64/boot.oat

**Comment by BurgerZ** [comment]
This is not a bug.
Redmi Note 2 has plugin directory with plugins, so if we deodex them, all plugins will have different signature, and system will reject them. To keep all things work you have to not deodex plugins and keep boot.oat files in framework directory.
I'll upload an update with options to choose directories to deodex, including plugin and vendor.

**Comment by ale8530** [comment]
Ok thanks a lot for this information are always very helpful :)

**Comment by vagyula1** [comment]
If i dont deodex the plugin folder, i cant use the extended reboot menu.

**Comment by BurgerZ** [comment]
@vagyula1 so patch signature checker (not recommended for security reasons)

**Comment by BurgerZ** [comment]
Added option to turn off deodexing of plugins dir https://github.com/BurgerZ/jBART/commit/19af788060297007cdcda8bd2512fba47f227d00
