### ISSUE TITLE
Problem Recompile WebViewGoogle.apk

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#139]
Jbart not recompile application WebViewGoogle.apk android 5.0

**Comment by jaymeferreyra** [comment]
You don't need to decompile it.
Just ignore that apk

**Comment by ale8530** [comment]
When I use "decompile src of each apk in ROM (Smali)" the system will automatically processes.

I have to use this feature to apply various patches

**Comment by BurgerZ** [comment]
As @jaymeferreyra mentioned, normally you don't need to decompile this apk. I will add exclusions list for decompilation process.

**Comment by ale8530** [comment]
Ok Thanks :)
