### ISSUE TITLE
Mi2s problem deodex

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#140]
Andrei, sorry to ask too many reports, but I wanted to tell you that the latest version of jbart fails to deodex of Mi2s

Thank's for your job

**Comment by BurgerZ** [comment]
Hm, mi2s was always deodexed. Even if there was odex files inside apk folders, there is classes.dex inside each apk, and no boot.oat framework files.
Is it odexed now? (really odexed, with boot.oat in framework/$arch dir)

**Comment by ale8530** [comment]
Within each app's file .odex, but in the framework folder is no boot.oat

**Comment by BurgerZ** [comment]
I meant classes.dex inside apk file

**Comment by ingbrzy** [comment]
yeap, Mi2 has dex files inside apks.. so no needs to deodex... just remove odex files or leave it there.. as you want...

**Comment by BurgerZ** [comment]
I'll try to add auto-remover for odexes if rom is deodexed

**Comment by ale8530** [comment]
Thanks ingbrzy and Andrei :)

**Comment by BurgerZ** [comment]
Fixed in https://github.com/BurgerZ/jBART/commit/5468cc5e0a0f926301d0ee14d7ddb120200c4c43
