### ISSUE TITLE
New compression system MIUI

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#142]
Hello Andrei,
last update Xiaomi used the new compression system Lollipop / Marshmallow for MI note Pro and Mi4c where all the information are contained in:

"system.new.dat"
"system.patch.dat"
"systam.transfer.list"

Do you think you can create an automatic decompression and deodex?

Thanks.

**Comment by BurgerZ** [comment]
I'll try, but later.

**Comment by ale8530** [comment]
Thanks ;)

**Comment by exodius48** [comment]
@BurgerZ why wontix? so its imposible to decompres & deodex it?

**Comment by BurgerZ** [comment]
This feature will not be available in public version of jbart (it's not worth the spent time).

**Comment by ngtruong1509** [comment]
I wanna use Paid version. Please tell me how to buy it?
