### ISSUE TITLE
Problems recompile with version 6.11.14

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#143]
Hello Andrei,
I wanted to alert these two cases with android 4.4:

1) ROM only deodex starts
2) ROM deodex with the only translation I get bootloop

Lollipop has not been tested.

Thanks for the great work you do for the whole community MIUI.

I hope they open soon to make a paypal donation :)

**Comment by BurgerZ** [comment]
So what is the problems??

**Comment by ale8530** [comment]
I point 2, if I insert the translation I bootloop

**Comment by BurgerZ** [comment]
And?
What is OS?

**Comment by ale8530** [comment]
sorry Andrei Linux 64-bit

Other information?

**Comment by ale8530** [comment]
What I'm trying to point out that after a recompile with the inclusion of the translation ROM goes bootloop.

If I only deodex this does not happen.

Andrei sorry I did not want to upset you.

**Comment by BurgerZ** [comment]
I'm not upset, believe me :)

**Comment by ale8530** [comment]
No problem ;), you encounter this problem?

**Comment by BurgerZ** [comment]
No

**Comment by ale8530** [comment]
I solved this problem by applying a patch to "services.jar" and copying the files AnalyticsCore.apk of deodex, if I use the apk recompiled not start the ROM, can be a problem of signature APK?

With Jbart "3h" I can recompile the single apk? Version "2a" I remember there was this feature

**Comment by BurgerZ** [comment]
1. Yes, the problem is that in services.jar there is a method that checks signatures of com.android.updater, com.xiaomi.market and com.***.securitycenter apps. If signature mismatch you'll get into bootloop.
2. Yes. In manual mode just press "S" to sign tha apk.

Closing this issue due to rom-related bootloop cause (signature checker)

**Comment by ale8530** [comment]
Thanks Andrei,
It will be introduced a Fix it?

**Comment by BurgerZ** [comment]
Fix? No, that is not jbart-related problem, that is rom's problem if they check for apk changes.

**Comment by ale8530** [comment]
Ok Thanks :)
