### ISSUE TITLE
Please, I can´t compile MIUI 7.1 system app using last app from you

### ISSUE THREAD

**Issue by jamflux** [BurgerZ/jBART#144]
Hello, thank you for your great work.
I have some issues compiling system apps from miui 7.1 hennesy phone, using xiaomi.eu ROM.
This ROM has some spanish errors in translation, I try to fix but changes were not applied.
Hope you can hel me. I can upload values-es folder with fixed translation, soy may me you can help me, I am a Windows user.
I appreciate all you do for me.
Thank you.

**Comment by BurgerZ** [comment]
Why not contanct xiaomi.eu directly to provide them your canges (or make pull request to Spanish repository)?
