### ISSUE TITLE
Problem recompile MIUI 7 android 6.

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#148]
Hello I would like,
report that there are some problems with recompilation of Android 6.0.

Many apps on Linux are not recompile for example:
Email.apk
ThemeManager.apk
framework-res.apk
Browser.apk
Settings.apk
Teleservice.apk

On Android 5.1.1 thanks to your suggestion this apk were ricompile on windows and allowed to have a fully translated rom.

Now with Android 6.0 as we can solve the problem?

**Comment by BurgerZ** [comment]
Hi. That is **apktool **related bugs, jbart has nothing to do with affecting apk files by itself.
