### ISSUE TITLE
Deodex android 7.0 not working

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#170]
Release jbart 20161212.01
Device: Xiaomi Mi5 android 7

Apk error:

CTNVItem.odex
BookmarkProvider.odex
Stk.odex
shutdownlistener.odex
XiaomiServiceFramework.odex
datastatusnotification.odex
PacProcessor.odex
BasicDreams.odex
GuardProvider.odex
XMPass.odex
TimeService.odex
Updater.odex
GameCenter.odex
NfcNci.odex
AppIndexProvider.odex
XiaomiVip.odex
SystemAdSolution.odex
SecurityAdd.odex
WallpaperBackup.odex
SampleExtAuthService.odex
MiPlay.odex
PrintSpooler.odex
SampleAuthenticatorService.odex
PicoTts.odex
KSICibaEngine.odex
fastdormancy.odex
NetworkAssistant2.odex
CertInstaller.odex
CaptivePortalLogin.odex
WfdService.odex
TSMClient.odex
FileExplorer.odex
SecureSampleAuthService.odex
PrintRecommendationService.odex
FidoCryptoService.odex
SSCMService.odex
QtiTelephonyService.odex
HTMLViewer.odex
PaymentService.odex
ModemTestMode.odex
Calculator.odex
PhotoTable.odex
DeskClock.odex
EasterEgg.odex
LiveWallpapersPicker.odex
ApplicationsProvider.odex
MiuiCompass.odex
ExtShared.odex
KeyChain.odex
SecureExtAuthService.odex
MiLinkService.odex
Bluetooth.odex
SmsExtra.odex
VoicePrintService.odex
XiaomiSimActivateService.odex
TouchAssistant.odex
AntHalService.odex
MiuiSuperMarket.odex
SeempService.odex
MiuiBluetooth.odex
XiaomiAccount.odex
com.qualcomm.qti.services.secureui.odex
CloudService.odex
Mipay.odex
SpacesCore.odex
BugReport.odex
UpnpService.odex
TranslationService.odex
NFCtestSvc.odex
com.quicinc.wbcserviceapp.odex
MiWallpaper.odex
FidoSuiService.odex
AntiSpam.odex
Notes.odex
Cit.odex
ThemeManager.odex
xdivert.odex
BluetoothMidiService.odex
SpacesPolicyApp.odex
embms.odex
AnalyticsCore.odex
SecurityCoreAdd.odex
btmultisim.odex
MiDrive.odex
CdmaCallOptions.odex
WAPPushManager.odex
UserDictionaryProvider.odex
miui.odex
uimremoteclient.odex
miuisystem.odex
InputDevices.odex
MiuiScanner.odex
QuickSearchBox.odex
MiVRFramework.odex
DownloadProviderUi.odex
ManagedProvisioning.odex
Shell.odex
MiuiVoip.odex
FindDevice.odex
BlockedNumberProvider.odex
WeatherProvider.odex
DocumentsUI.odex
YellowPage.odex
QFingerprintService.odex
MusicFX.odex
MediaProvider.odex
Calendar.odex
PersonalAssistant.odex
CNEService.odex
CalendarProvider.odex
Tag.odex
MiuiCamera.odex
MiuiSystemUI.odex
Provision.odex
DefaultContainerService.odex
SoundRecorder.odex
CleanMaster.odex
TeleService.odex
qcrilmsgtunnel.odex
Music.odex
ContactsProvider.odex
Telecom.odex
MiuiHome.odex
QtiTetherService.odex
MiuiVideo.odex
Settings.odex
Mms.odex
MmsService.odex
MiuiKeyguard.odex
ExternalStorageProvider.odex
Mipub.odex
CloudBackup.odex
Contacts.odex
MtpDocumentsProvider.odex
TelephonyProvider.odex
BackupRestoreConfirmation.odex
AuthManager.odex
CellBroadcastReceiver.odex
DownloadProvider.odex
SettingsProvider.odex
MiDrop.odex
MiuiGallery.odex
Browser.odex
VpnDialogs.odex
InCallUI.odex
ExtServices.odex
FingerprintServiceExtension.odex
ProxyHandler.odex
VirtualSim.odex
StatementService.odex
SmartcardService.odex
WallpaperCropper.odex
com.qualcomm.location.odex
CarrierConfig.odex
EmergencyInfo.odex
SecurityCenter.odex
OneTimeInitializer.odex
CallLogBackup.odex
Backup.odex
FusedLocation.odex
SharedStorageBackup.odex
dpmserviceapp.odex
Weather.odex
imssettings.odex
CABLService.odex
colorservice.odex
SVIService.odex
ims.odex

**Comment by BurgerZ** [comment]
Android 7 deodex is not supported yet!

**Comment by ale8530** [comment]
Thanks :)
