### ISSUE TITLE
Many errors deodex android 6.0 MIUI 8 

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#173]
There are various errors deodex with Android 6.0 MIUI 8.

Oat2dex-86.jar errors:

XiaomiAccount.apk

Oat2dex-87.jar errors:
GameCenter.apk
XiaomiVip.apk
MiuVideo.apk
XiaomiAccount.apk
Upnservice.apk
ecc.

Oat2dex-88.jar errors:

XiaomiAccount.apk

How to solve this problem?

**Comment by BurgerZ** [comment]
Use oat2dex-**0.86**.jar instead.

**Comment by ale8530** [comment]
I use this version if you see the list of errors

Oat2dex-86.jar errors:

XiaomiAccount.apk

**Comment by BurgerZ** [comment]
XiaomiAccount.apk is not deodexable by any of oat2dex.

**Comment by ale8530** [comment]
I can not use the baksmali/smali method jbart?

**Comment by BurgerZ** [comment]
jbart do not use baksmali/smali with 6.0 roms, so it could be a new feature: select what apk files should be deodexed with smali/baksmali.

**Comment by ale8530** [comment]
You could fix the various errors with deodex with oat2dex.jar. Thanks a lot in the future there will be this feature

**Comment by ale8530** [comment]
This issue fixed with release 20170605.05,but you have and bug, not deodex for gemini (Mi5) folder vendor/framework :)

**Comment by BurgerZ** [comment]
yep, already fixed that today. Wait for update.

**Comment by ale8530** [comment]
ok :)

**Comment by ale8530** [comment]
Fixed with last release
