### ISSUE TITLE
MIUI 7 based on Kitkat compile errors

### ISSUE THREAD

**Issue by dudjaa** [BurgerZ/jBART#175]
First of all thanks to the excellent work! I try to add the language in
MIUI 7 based on Android Kitkat, but I have too many errors. I also tried with Linux Ubuntu but without success. Some applications may not be compiled.

Is there a solution for this?
Thank you!

**Comment by BurgerZ** [comment]
> Is there a solution for this?
No. 
jbart itself do not decompile/compile apks. It uses apktool to do this apk stuff. So this issue is apktool related.
