### ISSUE TITLE
the line bar apk remove after compile jbart- please help

### ISSUE THREAD

**Issue by israrami** [BurgerZ/jBART#176]
hello, i try compile any app , but the problem that after compile i lost the bar top, and it be black always,the color on top of screen removed after compile, someone here know how to fix that , I want after compile all be green on top bar
please
help me

![41](https://cloud.githubusercontent.com/assets/26686760/24331750/4a764d90-1243-11e7-9e7d-611c0beb17be.jpg)

**Comment by KcNirvana** [comment]
Hello,
That is a problem of Apktool not Jbart.
You can put a issue https://github.com/iBotPeaches/Apktool/issues for more help
