### ISSUE TITLE
Not patched strings

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#177]
Jbart can not patch this string:

directory-->res/valus/strings.xml
![immagine](https://cloud.githubusercontent.com/assets/6189615/25744105/695b3fc6-3198-11e7-943a-e63e2bd2a206.png)

How can I fix it?

Thanks

**Comment by BurgerZ** [comment]
What?
Show me your patches.

**Comment by ale8530** [comment]
Patch-->[strings.xml.zip](https://github.com/BurgerZ/jBART/files/980145/strings.xml.zip)

I have set on xmlpatch.conf --> + string-array wifi_and_mobile_skipped_message

Log compiling-->![immagine](https://cloud.githubusercontent.com/assets/6189615/25762277/6c179f5c-31de-11e7-910f-830af841ce89.png)

Original strings:
![immagine](https://cloud.githubusercontent.com/assets/6189615/25762423/e9be51ee-31de-11e7-880c-ee58d0bc3469.png)

My first screenshot:

The first screenshot I've posted is the fix I need to do via strings.xml.part

Thanks for your attention

**Comment by ale8530** [comment]
The original string does not have the value highlighted in this screenshot, I have to put it in order to recompile it with apktool:

![immagine](https://cloud.githubusercontent.com/assets/6189615/25762713/2a0b58d6-31e0-11e7-8b44-3c862d71a86a.png)

**Comment by ale8530** [comment]
Is possibile applied an patch?

**Comment by ale8530** [comment]
I hade resolve this problem with nxt patch fuction replaceinfile :)
