### ISSUE TITLE
Bug compile "qihoo" ???

### ISSUE THREAD

**Issue by ghost** [BurgerZ/jBART#180]
1. [06.07.2017 04:49:18] I: **************************************************
2. [06.07.2017 04:49:18] I: Welcome to jBART v3h build 20170609.01
3. [06.07.2017 04:49:18] I: **************************************************
4. [06.07.2017 04:49:18] I: License info:
5. [06.07.2017 04:49:18] I: ID: c3244fb19029090e84a676548fb1242e
6. [06.07.2017 04:49:18] I: Name: Public
7. [06.07.2017 04:49:18] I: Serial: UNREGISTERED
8. [06.07.2017 04:49:18] I: License: license.lic
9. [06.07.2017 04:49:18] I: **************************************************
10. [06.07.2017 04:49:18] I: Java version: 1.8.0_131
11. [06.07.2017 04:49:18] I: OS name: Linux
12. [06.07.2017 04:49:18] I: OS version: 4.8.0-58-generic
13. [06.07.2017 04:49:18] I: OS arch: 64 bit
14. [06.07.2017 04:49:18] I: Home directory: /home/fayz/jBART/
15. [06.07.2017 04:49:18] I: 
16. [06.07.2017 04:49:18] I: 
17. [06.07.2017 04:49:18] I: ******** Compiling file started ********
18. [06.07.2017 04:49:18] I: **** Compiling Mi-Flower.apk ****
19. [06.07.2017 04:49:18] I: Using apktool-2.2.1-93a51c-SNAPSHOT.jar
20. [06.07.2017 04:49:18] I: I: Using Apktool 2.2.1-93a51c-SNAPSHOT
21. [06.07.2017 04:49:19] I: I: Copying /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk classes.dex file...
22. [06.07.2017 04:49:19] I: I: Building resources...
23. [06.07.2017 04:49:22] W: W: /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/AndroidManifest.xml:47: error: No resource identifier found for attribute 'qihoo' in package 'android'
24. [06.07.2017 04:49:22] W: W: 
25. [06.07.2017 04:49:22] W: W: /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/AndroidManifest.xml:47: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
26. [06.07.2017 04:49:22] W: W: 
27. [06.07.2017 04:49:22] W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_8809980573148972040.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 25, --version-code, 64, --version-name, 2.8.8, -F, /tmp/APKTOOL8002594073509314452.tmp, -0, arsc, -0, appkey, -0, so, -0, webp, -0, arsc, -I, /home/fayz/jBART/data/frameworks/1.apk, -S, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/res, -M, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/AndroidManifest.xml]
28. [06.07.2017 04:49:22] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:449)
29. [06.07.2017 04:49:22] W: 	at brut.androlib.Androlib.buildResources(Androlib.java:383)
30. [06.07.2017 04:49:22] W: 	at brut.androlib.Androlib.build(Androlib.java:310)
31. [06.07.2017 04:49:22] W: 	at brut.androlib.Androlib.build(Androlib.java:268)
32. [06.07.2017 04:49:22] W: 	at brut.apktool.Main.cmdBuild(Main.java:224)
33. [06.07.2017 04:49:22] W: 	at brut.apktool.Main.main(Main.java:84)
34. [06.07.2017 04:49:22] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -jar, /home/fayz/jBART/data/tools/lib/apktool-2.2.1-93a51c-SNAPSHOT.jar, b, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk, -f, -c, -p, /home/fayz/jBART/data/frameworks, -o, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/compiled/Mi-Flower.apk]
35. [06.07.2017 04:49:22] I: Time elapsed: 0h 0m 4s 621ms
36. [06.07.2017 04:49:22] W: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_8809980573148972040.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 25, --version-code, 64, --version-name, 2.8.8, -F, /tmp/APKTOOL8002594073509314452.tmp, -0, arsc, -0, appkey, -0, so, -0, webp, -0, arsc, -I, /home/fayz/jBART/data/frameworks/1.apk, -S, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/res, -M, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/AndroidManifest.xml]
37. [06.07.2017 04:49:22] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
38. [06.07.2017 04:49:22] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:435)
39. [06.07.2017 04:49:22] W: 	... 5 more
40. [06.07.2017 04:49:22] W: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_8809980573148972040.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 25, --version-code, 64, --version-name, 2.8.8, -F, /tmp/APKTOOL8002594073509314452.tmp, -0, arsc, -0, appkey, -0, so, -0, webp, -0, arsc, -I, /home/fayz/jBART/data/frameworks/1.apk, -S, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/res, -M, /home/fayz/jBART/projects/Mi-Flower.apk.bzprj/decompiled/Mi-Flower.apk/AndroidManifest.xml]
41. [06.07.2017 04:49:22] W: 	at brut.util.OS.exec(OS.java:95)
42. [06.07.2017 04:49:22] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
43. [06.07.2017 04:49:22] W: 	... 6 more

**Comment by BurgerZ** [comment]
I think you should post it at **apktool**'s issue tracker.
