### ISSUE TITLE
Support for recursively patching through dirs and subdirs

### ISSUE THREAD

**Issue by mattbittencourt** [BurgerZ/jBART#181]
Not an issue, it's a suggestion:

Is it possible to add support on smali patching to search recursively into a directory instead of directly specifying the smali? This should be useful for patching different Android bases, since sometimes the name of the final smali is different between Android versions :)

**Comment by BurgerZ** [comment]
`replaceinfile "%smali%/com/miui/permcenter/autostart" "sget-boolean v0, Lmiui/os/Build;->IS_INTERNATIONAL_BUILD:Z" "const/4 v0, 0x0";`
This patch will search for all smali files in `%smali%/com/miui/permcenter/autostart` directory and replace string `sget-boolean v0, Lmiui/os/Build;->IS_INTERNATIONAL_BUILD:Z` with `const/4 v0, 0x0`

**Comment by mattbittencourt** [comment]
Thanks for the clarification! :)
