### ISSUE TITLE
 Clarification request feature jbart

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#184]
Hello BurgerZ,
sorry for disturb how do you use this feature?

"Auto convert updater-script line endings to UNIX (LF) style if you edit/patch/copy/move or whatever you do with this file"

I should add four strings at the end of the updater-script, but if I use the "appendtofile" patch I insert only 1 string on four

**Comment by ale8530** [comment]
I have insert on anyfile_data.conf

appendtofile "%rom%/META-INF/com/google/android/updater-script" "ui_print("Installing custom recovery");";
appendtofile "%rom%/META-INF/com/google/android/updater-script" "ui_print("Flashing TWRP Touch recovery...");";
appendtofile "%rom%/META-INF/com/google/android/updater-script" "package_extract_file("recovery/twrp.img", "/dev/block/bootdevice/by-name/recovery");";
appendtofile "%rom%/META-INF/com/google/android/updater-script" "set_progress(1);";

Your tool insert only strings "set_progress(1);" why?

**Comment by BurgerZ** [comment]
Hi,

Yes, bug is accepted - every next string from the patch overwrites the previous one. I'll fix it soon.

**Comment by ale8530** [comment]
Thanks :)

**Comment by BurgerZ** [comment]
Fixed at https://github.com/BurgerZ/jBART/commit/2094ae3efc4aa7685eaab02f0c24bb51ab5bd4b5
