### ISSUE TITLE
Information add a comment to the build.prop

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#191]
From this update https://github.com/BurgerZ/jBART/commit/077d08b7bede2aaa783c958d2902e7931573808c "Added ability to add commented strings to build.pro (by buildprop_data.conf)" 

How can I add a comment? is not explained

**Comment by BurgerZ** [comment]
Described at https://github.com/BurgerZ/jBART/commit/2094ae3efc4aa7685eaab02f0c24bb51ab5bd4b5
