### ISSUE TITLE
Problem on GUI

### ISSUE THREAD

**Issue by bovirus** [BurgerZ/jBART#194]
@BurgerZ 

I sent an email to your email account but I didn't see an answer.
Please check it.
I found some problems on GUI of JBART.
Please check the screenshots attached to the email.

**Comment by BurgerZ** [comment]
I saw your email. I'll answer it when I have some time.

P.S. Very nice information, thanks.

**Comment by bovirus** [comment]
Hi.

Thanks.

Please if you can contact me in advance (you get my email address) before tor elase new version to test new version and language update.

Thanks.
