### ISSUE TITLE
add oem deodex

### ISSUE THREAD

**Issue by CrashX** [BurgerZ/jBART#197]
хорошо бы добавить деодекс oem раздела
а то приходиться руками копировать framework и содержание oem в отдельный архив для деодекса

спасибо

**Comment by CrashX** [comment]
раздел уже деодекс https://yadi.sk/d/jfYu7CHh3QrVPs

для деодекса я переименовывал oem в system и закидывал оригинальный odex framework
после удалял framework и переименовывал обратно

данный раздел стал использоваться на новых устройствах, обычно там build.prop был, но теперь там приложения, настройки, и даже встречаеются oem фреймворки

**Comment by CrashX** [comment]
нет это раздел oem, точка монтирования, рядом с system в корне

mount("ext4", "EMMC", "/dev/block/bootdevice/by-name/oem", "/oem", "max_batch_time=0,commit=1,data=ordered,barrier=1,errors=panic,nodelalloc");

ui_print("--> Wiping OEM...");
delete_recursive("/oem");  

ui_print("--> Installing oem...");
package_extract_dir("oem", "/oem");

ui_print("--> Correcting permissions...");
set_metadata_recursive("/oem", "uid", 0, "gid", 0, "dmode", 0755, "fmode", 0644, "capabilities", 0x0, "selabel", "u:object_r:system_file:s0");

**Comment by BurgerZ** [comment]
Я спрашивал про файл прошивки, где он в архиве находится, чтобы знать в какой папке распакованной прошивки искать файлы для деодекса :) Ведь барту все равно, куда он монтируется/копируется на устройстве.

**Comment by CrashX** [comment]
rom.zip
->oem
->system
->boot.img
