### ISSUE TITLE
Information for use log with file cli.recompile.conf

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#198]
I have appreciate this new feature:

- Logger: Updated logging framework. Logs are not written to files by default (to improve performance), added option to turn off logging, and button save log to file (if logging was not turned off)

But i have an demand for those using the cli.recompile.conf file, how can you get the log file in its default folder?

**Comment by BurgerZ** [comment]
Hi, 
There will be a set of options to tune logging (writing to files also).

**Comment by ale8530** [comment]
ok, so I wait for a next update?

**Comment by BurgerZ** [comment]
Updated jbart. You have an option to tune logging to write files. Look at the [samle](https://github.com/BurgerZ/jBART/blob/master/cli.conf.example)

**Comment by ale8530** [comment]
Very thanks :+1:
