### ISSUE TITLE
Clarification use patch with hex

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#202]
I have an question:

With apktool i have possibility the use this patch:

delete "%res%/values-mcc9998-mnc9999/colors.xml";
delete "%res%/values-mcc9998-mnc9999/fractions.xml";

With hex is possible?

MIUI has a serious problem of notifications for a long time, and to overcome this problem we need to patch the framework with Oreo if you use apktool you have bootloop, so the only hope is hex, how can I apply this type of patch?

**Comment by KcNirvana** [comment]
Hello,
I don't think you can delete resources with Hex since Hex doesn't decompile resources.arsc.
But have you tried to replace colors.xml with an empty file?
Like putting in you translation repo something like:
Res/Values-it
Res/values-mcc9998-mnc9999

The empty file should replace the original one with the Hex.
Just a sugestion

**Comment by BurgerZ** [comment]
There is no option yet to remove resources from resources.arsc, you can only replace them with yours.
Have you tried @KcNirvana's solution?

**Comment by ale8530** [comment]
I thank both for the advice, I have not tried, but you empty I mean that I have to put it so colors.xml or an xml file without text?
 
Example code:

<?xml version="1.0" encoding="utf-8"?>
<resources>
</resources>

**Comment by ale8530** [comment]
I thank both for the advice, I have not tried, but you empty I mean that I have to put it so colors.xml or an xml file without text?
 
Example code:

<?xml version="1.0" encoding="utf-8"?>
<resources>
</resources>

**Comment by ale8530** [comment]
@KcNirvana 
Do I enter the code this way?

![immagine](https://user-images.githubusercontent.com/6189615/34978138-814e5d38-fa9d-11e7-81c5-1b328162a8d7.png)

**Comment by KcNirvana** [comment]
@ale8530 
Good morning...
Yes...
Don't know if it will works, but if you don't test you will never know...
:)

**Comment by BurgerZ** [comment]
I think it will not work as no resources will be "replaced" or "added", so this step will be just skipped.
I have to add new HEX option - deleting configs (such as mnc/mcc/xxhdpi, etc.)

**Comment by ale8530** [comment]
@BurgerZ great feature for Hex very thanks

Do you have problems with MIUI notifications on a Chinese basis?

**Comment by BurgerZ** [comment]
I don't have any Xiaomi device (except kettler and vacuum robot) :D

**Comment by KcNirvana** [comment]
@ale8530 
Hello...
I tried to test like I said the empty file in Hex and I think it works, at least it appears in log.

> [19.01.2018 18:28:25] INFO: **** Recompiling Settings.apk ****
> [19.01.2018 18:28:25] INFO: Check for available NXT patches...
> [19.01.2018 18:28:25] INFO: Found NXT patches: 1
> [19.01.2018 18:28:25] INFO: Extracting classes.dex...
> [19.01.2018 18:28:26] INFO: Baksmaling classes.dex...
> [19.01.2018 18:28:28] INFO: Loading Patching configs...
> [19.01.2018 18:28:28] INFO: Loading NXT Patching configs...
> [19.01.2018 18:28:28] INFO: Smaling classes.dex...
> [19.01.2018 18:28:36] INFO: Zipping classes.dex...
> [19.01.2018 18:28:37] INFO: File classes.dex packed successfully
> [19.01.2018 18:28:38] INFO: Clearing directories and temp files...
> [19.01.2018 18:28:38] INFO:  
> [19.01.2018 18:28:38] INFO: Directory: res (1/5)
> [19.01.2018 18:28:40] INFO: Directory: values-mcc9998-mnc9999 (2/5)
> [19.01.2018 18:28:41] INFO: Processing colors...
> [19.01.2018 18:28:41] INFO:  Adding "default" translation
> [19.01.2018 18:28:44] INFO: Directory: raw-pt-rPT (3/5)
> [19.01.2018 18:28:45] INFO: Processing raw...
> [19.01.2018 18:28:45] INFO: Parsed locale:  (pt; PT)
> [19.01.2018 18:28:45] INFO:  Replacing "portuguese (portugal)" translation

I didn't try the rom built, so I can say if it really works or not.

**Comment by ale8530** [comment]
Really thanks, but it seems fortunately that Xiaomi has fixed the problem, we hope that Burgerz adds the function to delete certain files :)
