### ISSUE TITLE
Hex problem FC with Settings.apk

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#203]
I want to report a strange thing that happens with hex, in the latest updates xiaomi has introduced on Settings.apk the folder "assets / index.json", since it was inserted users started to have FC

**Step for reproduce:**
![54e42935-c84a-46c6-8bd7-e79bf380cf28](https://user-images.githubusercontent.com/6189615/34978350-3e75557e-fa9e-11e7-9ffe-21a95204d27b.jpg)

**FC:**
![8fae997c-f8c0-4de1-b797-36a74775bbcf](https://user-images.githubusercontent.com/6189615/34978424-78e715a8-fa9e-11e7-9a95-75745c57f926.jpg)

**Solution:**

I extracted the "assets/index.json" folder from Settings.apk before compiling once I have completed the folder inside the apk

It is not the most appropriate solution, but it works well, but I wanted to inform the developer, to understand the cause of this FC during the construction with HEX, just to point out, if I use Apktool FC does not manifest.

**File:**
[Settings.zip](https://github.com/BurgerZ/jBART/files/1634140/Settings.zip)

**Comment by BurgerZ** [comment]
You attached original apk or modified one?

**Comment by ale8530** [comment]
Original

**Comment by BurgerZ** [comment]
Could you send me hex'ed apk?

**Comment by ale8530** [comment]
yes thanks for investigate

[Settings_with_hex.zip](https://github.com/BurgerZ/jBART/files/1634455/Settings_with_hex.zip)

**Comment by BurgerZ** [comment]
And the last thing - can I get full text log from this FC (as I don't have any xiaomi phone)? :)

**Comment by ale8530** [comment]
Do you need a logcat? can I let you have another Xiaomi device?

**Comment by BurgerZ** [comment]
Yes, send me logcat, but important to get it when FC appears.

**Comment by ale8530** [comment]
I'll give you the logcat as soon as possible

**Comment by ale8530** [comment]
Just to keep up with the current Android 6.x devices that do not have that folder do not have FC

In the evening I send you logcat

**Comment by ale8530** [comment]
Here is the logcat, I checked and there is the error

[Logcat.zip](https://github.com/BurgerZ/jBART/files/1636654/Logcat.zip)

**Comment by ale8530** [comment]
Hello burgerZ news? :)

**Comment by BurgerZ** [comment]
give me your email (or contact me)

**Comment by ale8530** [comment]
My email is ale.8530@gmail.com
