### ISSUE TITLE
MIUI 10 Problem with HEX

### ISSUE THREAD

**Issue by ale8530** [BurgerZ/jBART#212]
Good evening,
I have the latest version of jbart and I need a verification from the developer, I correctly compiled the first MIUI 10 ROM for gemini, but I noticed a strange graphic problem:

![photo_2018-06-01_13-17-26](https://user-images.githubusercontent.com/6189615/40849878-73540ae8-65c3-11e8-8f90-7b296a4cdef9.jpg)

Apkoriginal-->[MiuiSystemUI.apk.zip](https://github.com/BurgerZ/jBART/files/2063277/MiuiSystemUI.apk.zip)

Frameworks-->[frameworks.zip](https://github.com/BurgerZ/jBART/files/2063278/frameworks.zip)

If you could kindly check if it could be a hex problem, with MIUI 9 android 8.0 I've never had any problems

Thanks for attention

**Comment by ale8530** [comment]
I have replace apk original and show toggles

![photo_2018-06-01_18-34-48](https://user-images.githubusercontent.com/6189615/40852443-c21fc840-65ca-11e8-9ee4-71687c71ebba.jpg)

It is a problem of hex therefore

**Comment by DriffeX** [comment]
Пробовал перевести хексом MiuiSystemUI.APK - NO PROBLEMO SIR MAN вроде))

**Comment by ale8530** [comment]
Driffex you have compile this apk with hex?

**Comment by ale8530** [comment]
It compiles to me without errors, but I have this graphic bug

**Comment by DriffeX** [comment]
Yes, I compile with hex - No problem with graphic. Do you use any patches?

**Comment by ale8530** [comment]
You have try full wipe?

**Comment by ale8530** [comment]
No I do not use that file configuration

**Comment by ale8530** [comment]
The strange thing, that the patches are always the same as when I use the original apk, with the Chinese one the toogles are seen without problem, the strange thing I compile it and whether I put Italian or other language the graphic defect remains.

**Comment by ale8530** [comment]
The bug is caused when you go to change the region via the build.prop, so the cause is not of hex, but of the MIUI

Thanks for help
