### ISSUE TITLE
Support decomp/recomp for extras apk

### ISSUE THREAD

**Issue by cpasmoi** [BurgerZ/jBART#32]
hello, it's possible to add an option to decompile and recompile apks found in extras repo ? 
thanks :+1:

**Comment by Zzzenk** [comment]
Why? You may decompile and compile again BEFORE you add it in repo...

**Comment by ygorigor** [comment]
+1

**Comment by BurgerZ** [comment]
How do you see this process?
Extras (replacements files) are copied to the ROM just before zipping it. So...  options:
1. Copy all files to the ROM, then recompile?
2. Recompile in downloaded repo, than copy to the ROM
3. ?
Where are translation files for replacements located? At the main repo?

**Comment by ygorigor** [comment]
I will use it for system apps that are often updated but wen a new ROM (i.e. VIBEUI) is released this apps are not included in ROM. So, if it's posible, add an option to jBART to replace existing old apps with new one and then decompile. Translation files are in main repo

**Comment by cpasmoi** [comment]
willl use for the xiaomi apps which i want to include (/data/miui/apps), the translations is on /main. :)

**Comment by BurgerZ** [comment]
extras repo files translatable - no sense
/data/miui/apps translatable - have sense
