### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by blackfa1con** [BurgerZ/jBART#73]
Hi , i have problem in the translations 
ok maybe you need to update the repo's bec there's many v5 repos not work well 
( translation_git_X' does not exist ) Like this ..
but after i updated the repos and compile the rom and change language to ex : Arabic i found that not all apps translated .
See the pic all the translations folder exist 
![x](https://cloud.githubusercontent.com/assets/6609410/6364313/f92314b8-bcb4-11e4-8978-11a10c9d9d82.png)

So where's the problem ? and how to fix it ?
Thank you :+1: 

Device GT-I9100
Rom MIUI-V5-4.4.4

**Comment by cpasmoi** [comment]
hello, check the jbart log, it will tell you about the problem.

 anyway i think many v5 repot are not longer updated and some are even very outdated, few of them probably have incompatibility (in number of arrays) wich cause Force Closes or bugs (when the language is activated)

**Comment by blackfa1con** [comment]
Yea I think so , in some languages the apps name not translated well , for example  in polish language the dailer app name not translated in other languages it translated so I think the problem in translations ....

By the way Jbart logs Always show
When compile back the apps this 

warning : string (  ......... ) not have  translation ... Etc 

Is this a problem ? 
Or what ?

**Comment by cpasmoi** [comment]
it mean the string  (.....) have no translation ... :D

**Comment by blackfa1con** [comment]
Hehehe :D 
its look like this 
>>

![2](https://cloud.githubusercontent.com/assets/6609410/6370472/f92a821e-bd01-11e4-8f6f-a717de63d1aa.png)

**Comment by blackfa1con** [comment]
Is there a solution or , I must translate the missing strings by my self ? :/

**Comment by BurgerZ** [comment]
"Has no default translation" means that string XXXX is translated in some language but there is no such string in default (values) folder. So you don't have to worry about such strings.

**Comment by blackfa1con** [comment]
Yea I Got it , thank you  :)
