### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by cpasmoi** [BurgerZ/jBART#79]
hello, there are one or 2 little details about translation, some things cannot be translated. it's not a big deal, but if you have some free time... ;)
the texts in the bottom bar cannot be translated "Compiling file :..." "Ready!" "Compiling file :" "Extracting rom" etc.
And also "Verbose output" checkbox in Single File tab.
thanks you :+1:

just close the ticket if it's boring for you, it don't matter much.

**Comment by BurgerZ** [comment]
I think that bottom (progress) text will not be translated. But It could be... I'll think about it.
Verbose output was made for tests, I forgot to translate it, will be fixed, thanks=)
