### ISSUE TITLE
com.android.systemui has stopped after add lang into v6 Mi3

### ISSUE THREAD

**Issue by symbianvn** [BurgerZ/jBART#86]
After used jbart add lang into v6 (Vietnamese), flashed this room. Open device, when open "recent task tray", it shoot me out to lock sceen.

![16806627816_50c2f85094_h](https://cloud.githubusercontent.com/assets/8969143/6680606/5b498d70-cc8c-11e4-9d12-58c270343b0a.jpg)

![16210139784_8032703a4b_h](https://cloud.githubusercontent.com/assets/8969143/6680610/620906ae-cc8c-11e4-8c5a-cd34e2c2114d.jpg)

How to fix it? Thanks!

**Comment by cpasmoi** [comment]
it's a tranlation issue, this translation is full of problem . use Parser in jbart to detect the errors.

**Comment by cpasmoi** [comment]
hello, it's not caused by a wrong variable as i said before, i was wrong. 

your translations files are up to date ?

**Comment by cpasmoi** [comment]
maybe the lock_screen_traffic_notify_body string but not sure if it's related to this problem i doubt. sorry for spamming..

**Comment by symbianvn** [comment]
I wll check again then report to you :)
Thanks!

**Comment by cpasmoi** [comment]
fixed ? :+1:
