### ISSUE TITLE
signing key rom not working on Mi note Pro (Default Mi Recovey)

### ISSUE THREAD

**Issue by igobig** [BurgerZ/jBART#97]
We are trying to translate MiNote PRO and Mi4i roms but we found that
zip file, is not working for those two devices and installation via updater app or MiRecovery failed.

**Comment by cpasmoi** [comment]
those 2 phones require rom signed with private keys, you need to flash special revovery before.

**Comment by cpasmoi** [comment]
check here for recovery : http://xiaomi.eu/community/link-forums/roms-download.73/
