### ISSUE TITLE
MIUI 6 (6.6.1.0 KHCMICF) Redmi 1S: Ringtone selection "other" option disapeared

### ISSUE THREAD

**Issue by ilopez85** [BurgerZ/jBART#99]
MIUI 6 (6.6.1.0 KHCMICF) Redmi 1S: Ringtone selection "other" option under sound settings disapeared after translate the ROM to spanish language.

**Comment by ygorigor** [comment]
Maybe this is a spanish language repo issue

**Comment by ilopez85** [comment]
This is the log of entire process: http://paste.omnirom.org/view/30839006

**Comment by ilopez85** [comment]
The ROM is in English by default, I should try to translate it into another language anyway.

**Comment by ilopez85** [comment]
There is an error with miui.apk, but I do not know if it will be the source of the problem.

Before translate:
http://i.imgur.com/0RE9bda.png?1

After translate:
http://i.imgur.com/DfgcNOA.png?1

**Comment by ilopez85** [comment]
https://github.com/ingbrzy/MA-XML-6.0-SPANISH/issues/70#issuecomment-124916988
